.PHONY: all
all:
	go install github.com/goreleaser/goreleaser
	go install honnef.co/go/tools/cmd/staticcheck
	go install github.com/gordonklaus/ineffassign
	go install github.com/nishanths/predeclared
	go install golang.org/x/lint/golint
	go install github.com/kisielk/errcheck
